apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
data:
  proxmox.yml: |-
    scrape_configs:
      - job_name: 'proxmox'
        static_configs:
          - targets:
            - 192.168.0.54:9221
        metrics_path: /pve
        params:
          module: [default]
      - job_name: 'node-exporter'
        static_configs:
          - targets:
            - 192.168.0.54:9100
        metrics_path: /metrics
        params:
          module: [default]
      - job_name: 'sensor-red'
        static_configs:
          - targets:
            - 192.168.0.101:80
            labels:
              room: 'bedroom'
        metrics_path: /metrics
        params:
          module: [default]
      - job_name: 'sensor-grey'
        static_configs:
          - targets:
            - 192.168.0.104:80
            labels:
              room: 'workroom'
        metrics_path: /metrics
        params:
          module: [default]
      - job_name: 'sensor-yellow'
        static_configs:
          - targets:
            - 192.168.0.105:80
            labels:
              room: 'livingroom'
        metrics_path: /metrics
        params:
          module: [default]