apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-loki-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: monitoring
    name: storage-loki-0
  nfs:
    path: "/mnt/ssd/loki"
    server: "192.168.0.54"
    readOnly: false