apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Time to reassignment in seconds
  timeout.reconciliation: "180"
  # Default allows empty namespaces in destinations
  application.namespaces: ""
