# Used https://dev.to/seewhy/using-helm-chart-to-deploy-grafana-prometheus-and-loki-data-source-on-your-kubernetes-cluster-1287

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
- default.addresspool.yaml
- metallb.yaml
