global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - 'prometheus:9090'
- job_name: 'docker'
  static_configs:
  - targets: 
    - 'host.docker.internal:9323'
- job_name: "node"
  static_configs:
  - targets: 
    - "node-exporter:9100"
- job_name: "cadvisor"
  static_configs:
  - targets:
    - "cadvisor:8080"
- job_name: 'nextcloud-exporter'
  static_configs:
  - targets: 
    - 'nextcloud-exporter:9205'
- job_name: 'mysql-exporter'
  static_configs:
  - targets:
    - "mysql-exporter:9104"
- job_name: 'fritz-exporter'
  static_configs:
  - targets:
    - "fritz-exporter:9787"
