apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certbot-secret-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["cert", "cert-test"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certbot-secret-manager
  namespace: default
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: default
roleRef:
  kind: Role
  name: certbot-secret-manager
  apiGroup: rbac.authorization.k8s.io